repository: gabeluci/gabeluci.github.io
theme: jekyll-theme-dinky
title: Gabe's Code
description: Stuff I've learned along the way
comments_locked: false

reCaptcha:
  siteKey: "6Lel8YUUAAAAAJkNXVJ1SwFHPPtrm6cuzu_9Zmms"
